### ISSUE TITLE
/validate/key接口没有写入cookie

### ISSUE THREAD

**Issue by SkateHaozi** [youbl/study#14]
![image](https://github.com/youbl/study/assets/45562192/bc8493da-d711-427c-8ff0-d1ae1531988d)
如图，博客里写的是二次验证成功的cookie需要写入response，但是beinet.cn.googleauthenticatordemo.authenticator.AuthenticatorService#validateCode方法里并没有实现，只返回了boolean

**Comment by youbl** [comment]
AuthenticatorService只负责密钥读写 和比对验证码的业务逻辑，不参与cookie这种业务上下文逻辑。

写入Cookie的地方 放在Controller层了，业务比对无误时，把Cookie写入Controller的上下文：
configs\loginAction\OtpController.java

**Comment by SkateHaozi** [comment]
所以CodeController和OtpController的关系是？看起来它们实现了相似的接口

**Comment by youbl** [comment]
CodeController应该是没有使用，应该是一开始用于测试的一个类，可以移除
